config/routes.rb
Rails.application.routes.draw do
  root 'groups#index'
  devise_for :users
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:index, :new, :edit, :create, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  has_many :groups_users
  has_many :users, through: :groups_users
  has_many :messages
end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name,:email, presence: true
  has_many :groups_users
  has_many :groups, through: :groups_users
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :move_to_sign_in
    before_action :set_group, only:[:edit,:update]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
     @group = Group.new(group_params)
    if @group.save
      redirect_to group_messages_path(@group), notice: 'グループを作成しました。'
   else
      render :new
    end
  end
  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを編集しました。'
    else
      render :edit
    end
  end

  private
    def group_params
       params.require(:group).permit(:name, :user_ids => [])
    end
    def set_group
       @group = Group.find(params[:id])
    end

    def move_to_sign_in
          redirect_to new_user_session_path unless user_signed_in?
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :move_to_sign_in
    before_action :set_group
    before_action :set_groups
    before_action :set_messages

  def index
    @message = Message.new
    respond_to do |format|
     format.html
     format.json
    end
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path, notice: '投稿しました。'}
        format.json
      end
    else
      flash.now[:alert] = 'メッセージの入力、もしくは画像の選択をしてください'
      render :index
    end
  end

  private
  def message_params
     params.require(:message).permit(:content, :image).merge(user_id: current_user.id,group_id: params[:group_id])
  end

  def move_to_sign_in
        redirect_to new_user_session_path unless user_signed_in?
  end

  def set_group
       @group = Group.find(params[:group_id])
  end

  def set_groups
       @groups = current_user.groups
  end

  def set_messages
       @messages = @group.messages
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end
  def update
    @user = User.find(params[:id])
    if
      @user.update(user_params)
      redirect_to :root
    else
      render "edit"
    end
  end

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%")
    respond_to do |format|
     format.json
   end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_flash.html.haml
- if @group.errors.any?
  .chat-group-form__errors
    %h2
      = @group.errors.count
      件のエラーがあります。
    %ul
      - @group.errors.full_messages.each do |msg|
        %li= msg

app/views/groups/_group.html.haml
.group-content
  %p.group-content__group-name
    =link_to group.name, group_messages_path(group)
  - if group.messages.last
    %p.group-content__group-comment=group.messages.last.content
  - else
    %p.group-content__group-comment まだコメントはありません

app/views/groups/_user.html.haml
.user-contents
  %h3.user-contents__username=current_user.name
  %ul
    %li
      =link_to edit_user_registration_path do
        %i.fa.fa-cog.icon
    %li
      =link_to new_group_path do
        %i.fa.fa-pencil-square-o.icon

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for(@group) do |f|
    = render partial: "flash"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat-group-form__input', placeholder: "グループ名を入力してください", value: "#{@group.name}"
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
      /
        <div class='chat-group-form__field--left'>
        <label class="chat-group-form__label" for="chat_group_チャットメンバーを追加">チャットメンバーを追加</label>
        </div>
        <div class='chat-group-form__field--right'>
        <div class='chat-group-form__search clearfix'>
        <input class='chat-group-form__input' id='user-search-field' placeholder='追加したいユーザー名を入力してください' type='text'>
        </div>
        <div id='user-search-result'></div>
        </div>
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "チャットメンバー", class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |b|
          = b.label { b.check_box + b.text }
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        %input.chat-group-form__action-btn{"data-disable-with" => "Save", :name => "commit", :type => "submit", :value => "Save"}/

app/views/groups/index.html.haml
%body
  .wrapper
    .usergroup
      = render partial: "user"
      .group_contents
        = render @groups

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for(@group) do |f|
    = render partial: "flash"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat-group-form__input', placeholder: "グループ名を入力してください"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "チャットメンバーを追加", class: 'chat-user-form__label'
      .chat-group-form__field--right
        %input.chat-user-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
        .chat-group-form__search.clearfix
          #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "チャットメンバー", class: 'chat-group-form__label'
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix.js-chat-member
            %input{name: "group[user_ids][]", type: "hidden", value: "#{current_user.id}"}/
            %p.chat-group-user__name=current_user.name
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        %input.chat-group-form__action-btn{"data-disable-with" => "Save", name:"commit", type:"submit", value:"登録する"}/

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_chat-header.html.haml
.chat-header
  %p.chat-header__group-name= @group.name
  %p.chat-header__chat-edit Edit
  %p.chat-header__chat-member Member : z13_masahiro

app/views/messages/_message.html.haml
.chat-content
  %ul.clearfix
    %li
      %p.chat-content__chat-name=current_user.name
    %li
      %p.chat-content__chat-date=message.created_at.strftime('%Y年%m月%d日 %H:%M')
    %br
    %li
      %p.chat-content__chat-message
      =message.content
      %p.chat-content__chat-image
      =image_tag message.image.to_s

app/views/messages/index.html.haml
%body
  .wrapper
    .usergroup
      = render partial: "groups/user"
      .group_contents
        = render @groups
    .chat
      = render partial: "chat-header"
      .chat-contents
        = render @messages
      .chat-footer
        = form_for([@group,@message]) do |f|
          %ul
            %li.message
              = f.text_field :content, class:'chat-footer__message-form', placeholder:' type a message'
            %li
              %p.chat-footer__picture
                = f.file_field :image, class:'chat-footer__image-hidden'
                = f.label :image do
                  %i.fa.fa-image
            %li
              = f.submit "Send", class:'chat-footer__send'